[package]
name = "jwt_actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.38"
futures = "0.3.30"
futures-util = "0.3.30"
jsonwebtoken = "9.3.0"
serde = "1.0.208"
