[package]
name = "uuid_versions"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "tls-rustls"] }
tokio = { version = "1.38.1", features = ["full"] }
uuid = { version = "1.10.0", features = ["fast-rng", "v4", "v7"] }
