services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432"
    environment:
      POSTGRES_USER: egor
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    command: >
      bash -c "
      psql -U postgres -c 'CREATE EXTENSION IF NOT EXISTS pg_uuidv7;'
      && postgres
      "
    restart: unless-stopped
volumes:
  postgres-data:
